#server:
#  port: 8012
#spring:
#  application:
#    name: demo2-service
#
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_ysxt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#
#  #  Redis配置
#  data:
#    redis:
#      host:  localhost
#      port:  6379
#      database: 0
#      password: 123456
#      lettuce:
#        pool:
#          max-active: 8
#          max-wait: -1
#          max-idle: 8
#          min-idle: 0
#
## 配置mybatis的xml文件路径
#mybatis:
#  mapper-locations: classpath*:mappers/**/*.xml
#
#some:
#  property: "测试配置中心，打印出来了就代表连接上了"
#
#common_name: common-service
#common_url: 'localhost:8010'
#
#demo1_name: demo1-service
#demo1_url: 'localhost:8011'
#
#demo2_name: demo2-service
#demo2_url: 'localhost:8012'