server:
  port: 8011  # 服务器端口配置

spring:
  application:
    name: demo1-service  # Spring应用名称配置

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 驱动类名
    url: jdbc:mysql://localhost:3306/db_ysxt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai  # 数据库URL
    username: root  # 用户名
    password: 123456  # 密码

  #  Redis配置
  data:
    redis:
      host:  localhost  # Redis主机地址
      port:  6379  # Redis端口
      database: 0  # Redis数据库编号
      password: 123456  # Redis密码
      lettuce:
        pool:
          max-active: 8  # 最大活动连接数
          max-wait: -1  # 最大等待时间，-1表示不等待
          max-idle: 8  # 最大空闲连接数
          min-idle: 0  # 最小空闲连接数

# 配置mybatis的xml文件路径
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml  # Mybatis XML文件路径


# 配置中心相关配置
some:
  property: "测试配置中心，打印出来了就代表连接上了"

common_name: common-service  # 配置中心服务名称
common_url: 'localhost:8010'  # 配置中心服务URL

demo1_name: demo1-service  # 服务名称
demo1_url: 'localhost:8011'  # 服务URL

demo2_name: demo2-service  # 服务名称
demo2_url: 'localhost:8012'  # 服务URL
